env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s # время на чтение запроса и такое же время на отпавке ответа, время на обработку не ограничено
  idle_timeout: 60s # время жизни соединения с клиентом
  user: "myuser"
  password: "mypass"